name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.80.1
  RUST_VERSION_NIGHTLY: nightly-2021-03-25
  MUTAGEN_COMMIT: f8249256c40769c916b5b00bd284f204d5540588
  COV_THRESHOLD: 100.0
  MUTAGEN_THRESHOLD: 100.0
  CRATE_PATHS: .
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_VERSION_STABLE }}
        profile: release
        override: true
    - name: Building
      run: cargo build --release --all-targets
    - name: Checking
      run: cargo c
    - name: Testing
      run: cargo t
  lint-rust:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: release
          components: rustfmt, clippy
          override: true
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings $(cat .lints | cut -f1 -d"#" | tr '\n' ' ')
      - name: Run rustfmt
        run: cargo fmt -- --check
